package main.java.model;
// Generated Jun 17, 2018 7:19:45 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChiTietMuonTra generated by hbm2java
 */
@Entity
@Table(name = "chi_tiet_muon_tra", catalog = "library")
public class ChiTietMuonTra implements java.io.Serializable {

	private Integer id;
	private MuonTra muonTra;
	private Sach sach;
	private String ngayMuon;
	private int soLuong;
	private boolean xacNhanTra;

	public ChiTietMuonTra() {
	}

	public ChiTietMuonTra(MuonTra muonTra, Sach sach, String ngayMuon, int soLuong, boolean xacNhanTra) {
		this.muonTra = muonTra;
		this.sach = sach;
		this.ngayMuon = ngayMuon;
		this.soLuong = soLuong;
		this.xacNhanTra = xacNhanTra;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_PHIEU_MUON_TRA", nullable = false)
	public MuonTra getMuonTra() {
		return this.muonTra;
	}

	public void setMuonTra(MuonTra muonTra) {
		this.muonTra = muonTra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_SACH", nullable = false)
	public Sach getSach() {
		return this.sach;
	}

	public void setSach(Sach sach) {
		this.sach = sach;
	}

	@Column(name = "NGAY_MUON", nullable = false, length = 10)
	public String getNgayMuon() {
		return this.ngayMuon;
	}

	public void setNgayMuon(String ngayMuon) {
		this.ngayMuon = ngayMuon;
	}

	@Column(name = "SO_LUONG", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "XAC_NHAN_TRA", nullable = false)
	public boolean isXacNhanTra() {
		return this.xacNhanTra;
	}

	public void setXacNhanTra(boolean xacNhanTra) {
		this.xacNhanTra = xacNhanTra;
	}

}
