package main.java.model;
// Generated Jun 17, 2018 7:19:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MuonTra generated by hbm2java
 */
@Entity
@Table(name = "muon_tra", catalog = "library")
public class MuonTra implements java.io.Serializable {

	private Integer id;
	private String mssv;
	private String nameSv;
	private String lopSv;
	private Boolean status;
	

	public MuonTra() {
		
	}
	public MuonTra(int id) {
		this.id = id;
	}
	public MuonTra(String mssv, String nameSv, String lopSv) {
		this.mssv = mssv;
		this.nameSv = nameSv;
		this.lopSv = lopSv;
	}

	public MuonTra(String mssv, String nameSv, String lopSv, Boolean status) {
		this.mssv = mssv;
		this.nameSv = nameSv;
		this.lopSv = lopSv;
		this.status = status;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "MSSV", nullable = false, length = 20)
	public String getMssv() {
		return this.mssv;
	}

	public void setMssv(String mssv) {
		this.mssv = mssv;
	}

	@Column(name = "NAME_SV", nullable = false, length = 30)
	public String getNameSv() {
		return this.nameSv;
	}

	public void setNameSv(String nameSv) {
		this.nameSv = nameSv;
	}

	@Column(name = "LOP_SV", nullable = false, length = 20)
	public String getLopSv() {
		return this.lopSv;
	}

	public void setLopSv(String lopSv) {
		this.lopSv = lopSv;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	

}
