package main.java.model;
// Generated Jun 17, 2018 7:19:45 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhan_vien", catalog = "library")
public class NhanVien implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String pass;
	private String phone;
	private String name;
	private String address;
	private boolean status;

	public NhanVien() {
	}

	public NhanVien(String userName, String pass, String phone, String name, boolean status) {
		this.userName = userName;
		this.pass = pass;
		this.phone = phone;
		this.name = name;
		this.status = status;
	}

	public NhanVien(String userName, String pass, String phone, String name, String address, boolean status) {
		this.userName = userName;
		this.pass = pass;
		this.phone = phone;
		this.name = name;
		this.address = address;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASS", nullable = false, length = 50)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "PHONE", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "STATUS", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
