package main.java.model;
// Generated Jun 17, 2018 7:19:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name = "sach", catalog = "library")
public class Sach implements java.io.Serializable {

	private Integer id;
	private TheLoai theLoai;
	private String name;
	private int soLuong;
	private int soTrang;
	private int namXuatBan;
	private String nhaXuatBan;
	private String tacGia;
	private boolean trangThai;
	private String ghiChu;
	

	public Sach() {
	}

	public Sach(TheLoai theLoai, String name, int soLuong, int soTrang, int namXuatBan, String nhaXuatBan,
			String tacGia, boolean trangThai) {
		this.theLoai = theLoai;
		this.name = name;
		this.soLuong = soLuong;
		this.soTrang = soTrang;
		this.namXuatBan = namXuatBan;
		this.nhaXuatBan = nhaXuatBan;
		this.tacGia = tacGia;
		this.trangThai = trangThai;
	}

	public Sach(TheLoai theLoai, String name, int soLuong, int soTrang, int namXuatBan, String nhaXuatBan,
			String tacGia, boolean trangThai, String ghiChu) {
		this.theLoai = theLoai;
		this.name = name;
		this.soLuong = soLuong;
		this.soTrang = soTrang;
		this.namXuatBan = namXuatBan;
		this.nhaXuatBan = nhaXuatBan;
		this.tacGia = tacGia;
		this.trangThai = trangThai;
		this.ghiChu = ghiChu;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "THE_LOAI", nullable = false)
	public TheLoai getTheLoai() {
		return this.theLoai;
	}

	public void setTheLoai(TheLoai theLoai) {
		this.theLoai = theLoai;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SO_LUONG", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "SO_TRANG", nullable = false)
	public int getSoTrang() {
		return this.soTrang;
	}

	public void setSoTrang(int soTrang) {
		this.soTrang = soTrang;
	}

	@Column(name = "NAM_XUAT_BAN", nullable = false)
	public int getNamXuatBan() {
		return this.namXuatBan;
	}

	public void setNamXuatBan(int namXuatBan) {
		this.namXuatBan = namXuatBan;
	}

	@Column(name = "NHA_XUAT_BAN", nullable = false, length = 30)
	public String getNhaXuatBan() {
		return this.nhaXuatBan;
	}

	public void setNhaXuatBan(String nhaXuatBan) {
		this.nhaXuatBan = nhaXuatBan;
	}

	@Column(name = "TAC_GIA", nullable = false, length = 30)
	public String getTacGia() {
		return this.tacGia;
	}

	public void setTacGia(String tacGia) {
		this.tacGia = tacGia;
	}

	@Column(name = "TRANG_THAI", nullable = false)
	public boolean isTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(boolean trangThai) {
		this.trangThai = trangThai;
	}

	@Column(name = "GHI_CHU", length = 100)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	

}
