package main.java.model;
// Generated Jun 17, 2018 7:19:45 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TheLoai generated by hbm2java
 */
@Entity
@Table(name = "the_loai", catalog = "library")
public class TheLoai implements java.io.Serializable {

	private Integer id;
	private String name;
	private String note;
	private Boolean status;
	

	public TheLoai() {
	}

	public TheLoai(String name) {
		this.name = name;
	}

	public TheLoai(String name, String note, Boolean status) {
		this.name = name;
		this.note = note;
		this.status = status;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NOTE", length = 30)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	

}
